# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RTPbSAD9lrJYUCJWltPXAPyuv3UbwPs
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('Student_engagement.csv')
df.head()

df.info()
df.describe(include='all')
df.isnull().sum()

df = df.rename(columns={
    "Student_ID": "student_id",
    "Course_ID": "course_id",
    "Login_Frequency": "logins",
    "Time_Spent_Modules": "time_spent",
    "Participation_Forums": "forum_posts",
    "Quiz_Performance_Average": "quiz_score",
    "Assignment_Submissions": "assignments",
    "Resource_Access_Frequency": "resource_access",
    "Session_Duration_Average": "session_duration",
    "Device_Type": "device",
    "Internet_Bandwidth": "bandwidth",
    "Facial_Expression_Engagement": "facial_engagement",
    "Emotional_State": "emotion",
    "Engagement_Level": "engagement_level"
})
df.head()

#Engagement Score (custom formula)
df["engagement_score"] = (
    df["logins"] * 0.3 +
    df["time_spent"] * 0.4 +
    df["forum_posts"] * 0.3
)

#High / Medium / Low Activity Labels
df["activity_level"] = pd.qcut(
    df["engagement_score"],
    3,
    labels=["Low", "Medium", "High"]
)

# Dropout Indicator
df["dropout_flag"] = (
    (df["engagement_level"].isin(["Inactive","Sparsely Involved"])) &
    (df["logins"] <= 3) &
    (df["time_spent"] < 10)
)

df["completed"] = (
    (df["engagement_level"] == "Highly Active") &
    (df["quiz_score"] >= 70)
)

course_completion = df.groupby("course_id")["completed"].mean().sort_values(ascending=False)
course_completion.head()

##Calculate Course Completion %
df["completed"] = (
    (df["engagement_level"] == "Highly Active") &
    (df["quiz_score"] >= 70)
)
#Course-wise completion rate:
course_completion = df.groupby("course_id")["completed"].mean().sort_values(ascending=False)
course_completion.head()

#Total Engagement Trends
#Average engagement by course:
engagement_by_course = df.groupby("course_id")["engagement_score"].mean().sort_values(ascending=False)
engagement_by_course.head()
#Engagement by activity level:
df["activity_level"].value_counts()

#Correlation Analysis
df[["engagement_score", "quiz_score", "assignments", "resource_access", "time_spent"]].corr()

#Visualizations (Colab, using Matplotlib)
import matplotlib.pyplot as plt

top10 = engagement_by_course.head(10)
top10.plot(kind="bar", figsize=(10,5),color = "#FFBDBD",edgecolor="#FFA4A4")
plt.title("Top 10 Courses by Engagement")
plt.xlabel("Course")
plt.ylabel("Engagement Score")
plt.show()

#Distribution of Activity Levels
colors = ["#BADFDB", "#FFA4A4", "#FFBDBD"]
df["activity_level"].value_counts().plot(kind="pie", colors = colors,autopct="%1.1f%%")
plt.title("Activity Levels Distribution")
plt.show()

#Engagement vs Quiz Score
plt.scatter(df["engagement_score"], df["quiz_score"],color = "#BADFDB")
plt.xlabel("Engagement Score")
plt.ylabel("Quiz Score")
plt.title("Engagement vs Quiz Performance")
plt.show()

#Assignment Patterns
assignment_patterns = df.groupby("course_id")["assignments"].mean().sort_values()
assignment_patterns.head()
assignment_patterns.plot(kind="bar", figsize=(12,5),color = "#FFBDBD",edgecolor="#FFA4A4")
plt.title("Average Assignment Submissions per Course")
plt.show()

#Find Most Popular Courses
popular_courses = df["course_id"].value_counts().head(10)
print(popular_courses)

student_completion = df.groupby("student_id")["completed"].mean()*100

#download the file in .xlsx
df.to_excel("student_engagement_cleaned.xlsx", index=False)
from google.colab import files
files.download("student_engagement_cleaned.xlsx")

